project/config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get "products/do" => "products#do"
  get "carts/create_order"
  get "set_seller" => "application#set_seller"
  get "set_customer" => "application#set_customer"


  resources :product_orders
  resources :orders
  resources :collections
  resources :carts
  
  resources :products do
    resources :specs
  end
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "products#index"

end

project/app/models/spec.rb
class Spec < ApplicationRecord
    belongs_to :product
    has_many :carts, dependent: :destroy
    has_many :productOrders, dependent: :destroy
end

project/app/controllers/specs_controller.rb
class SpecsController < ApplicationController
  before_action :set_spec, only: %i[ show edit update destroy ]
  before_action :set_product

  # GET /specs or /specs.json
  def index
    @specs = @product.specs.all
  end

  # GET /specs/1 or /specs/1.json
  def show
  end

  # GET /specs/new
  def new
    @spec = @product.specs.new
  end

  # GET /specs/1/edit
  def edit
  end

  # POST /specs or /specs.json
  def create
    @spec = @product.specs.new(spec_params)

    # respond_to do |format|
      if @spec.save
        redirect_to product_path(@product), notice: "Spec was successfully created."
        # format.html { redirect_to @spec, notice: "Spec was successfully created." }
        # format.json { render :show, status: :created, location: @spec }
      else
        # format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @spec.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /specs/1 or /specs/1.json
  def update
    # respond_to do |format|
      if @spec.update(spec_params)
        redirect_to product_path(@product), notice: "Spec was successfully updated."
        # format.html { redirect_to @spec, notice: "Spec was successfully updated." }
        # format.json { render :show, status: :ok, location: @spec }
      else
        # format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @spec.errors, status: :unprocessable_entity }
      end
    # end
  end

  # DELETE /specs/1 or /specs/1.json
  def destroy
    @spec.destroy
    redirect_to product_path(@product), notice: "Spec was successfully destroyed."
    # respond_to do |format|
    #   format.html { redirect_to specs_url, notice: "Spec was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_spec
      @spec = Spec.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spec_params
      params.require(:spec).permit(:title, :product)
    end
end

project/app/helpers/specs_helper.rb
module SpecsHelper
end

project/app/views/specs/_form.html.erb
<div class="form" >
  <%= form_with(model: [@product, spec]) do |form| %>
    <% if spec.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(spec.errors.count, "error") %> prohibited this spec from being saved:</h2>

        <ul>
          <% spec.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="actions">
      <%= form.submit :Submit, style:'border-radius: 5px; height: 40px; width: 80%; margin-left: 10%;' %>
    </div>
  <% end %>
</div>

project/app/views/specs/edit.html.erb
<h1 class="header-form">Editing Spec</h1>

<%= render 'form', spec: @spec %>

<%= link_to 'Show', product_spec_path(@product,@spec) %> |
<%= link_to 'Back', product_specs_path(@product) %>

project/app/views/specs/index.html.erb
<h1>Specs</h1>

<div>
  
<div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specs.each do |spec| %>
      <tr>
        <td><%= spec.title %></td>
        <td><%= link_to 'Show', product_spec_path(@product, spec) %></td>
        <td><%= link_to 'Edit', edit_product_spec_path(@product, spec) %></td>
        <td><%= link_to 'Destroy', product_spec_path(@product, spec), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spec', new_product_spec_path(@product) %>

project/app/views/specs/new.html.erb
<h1 class="header-form">New Spec</h1>

<%= render 'form', spec: @spec %>

<%#= link_to 'Back', product_specs_path %>

project/app/views/specs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @spec.title %>
</p>

<%= link_to 'Edit', edit_product_spec_path(@product,@spec) %> |
<%= link_to 'Back', product_specs_path(@product) %>