project/config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get "products/do" => "products#do"
  get "carts/create_order"
  get "set_seller" => "application#set_seller"
  get "set_customer" => "application#set_customer"


  resources :product_orders
  resources :orders
  resources :collections
  resources :carts
  
  resources :products do
    resources :specs
  end
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "products#index"

end

project/app/views/layouts/_NavBar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:10px;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">JQShop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Promotions</a>
        </li>
      </ul>
        
      <ul class="navbar-nav navbar-expand-lg mr-auto">
        <% if user_signed_in? && current_user.customer? %> 
          <li class="nav-item">
            <div class="nav-link">
              <%= link_to 'Carts', carts_path , style:"color: black; text-decoration:none;"%>
            </div>
          </li>
        <% end %>

        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if current_user.seller? %>
              <li class="dropdown-item">
                <%= link_to "Add Product", new_product_path, style:"color:black; text-decoration:none;"%>
              </li>
            <% end %>
            <% if current_user.customer? %>
              <li class="dropdown-item">
                <%= link_to "Collections", collections_path, style:"color:black; text-decoration:none;"%>
              </li>
            <% end %>
            <li class="dropdown-item">
              <%= link_to "Orders", orders_path, style:"color:black; text-decoration:none;"%>
            </li>
            <li><hr class="dropdown-divider"></li>
              <li class="dropdown-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: "Are you sure you wanna log out?"}, style:"color: grey; text-decoration:none;"%>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item navbar-button">
            <button class="btn btn-dark" style="margin:0 5px;">
              <%= link_to "Sign Up", new_user_registration_path, style:"color: white; text-decoration:none;"%>
            </button>
          </li>
          <li class="nav-item">
            <button class=" btn btn-dark" style="margin:0 5px;">
              <%= link_to "Log In", new_user_session_path, style:"color: white; text-decoration:none;"%>
            </button
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

project/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>Project</title>
  </head>
  <body>
    <%= render "layouts/NavBar" %>
    
    <% if notice %>
      <div id='notice'>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>