project/config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  get "products/do" => "products#do"
  get "carts/create_order"
  get "set_seller" => "application#set_seller"
  get "set_customer" => "application#set_customer"


  resources :product_orders
  resources :orders
  resources :collections
  resources :carts
  
  resources :products do
    resources :specs
  end
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "products#index"

end

project/app/models/product.rb
class Product < ApplicationRecord
    after_initialize :set_default, :if => :new_record?

    has_one_attached :image, dependent: :destroy
    has_many :specs, dependent: :destroy
    belongs_to :seller, class_name: "User"
    has_many :collections, dependent: :destroy
    has_many :productOrders, dependent: :destroy
    has_many :comments, dependent: :destroy

    def set_default
        self.sold = 0
        self.save()
    end
end

project/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit do update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @current = -1
    @specs = @product.specs.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @seller = User.find(current_user.id)
    @product = Product.new(product_params)
    @product.seller = @seller

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def do
    @product = Product.find(params[:product_id])
    @quantity = params[:quantity]
    if params[:commit] == "Buy Now" 
        @item = {quantity: @quantity, spec_id: params[:spec_id]}
        redirect_to new_order_path(items: [@item]) 
    elsif params[:commit] == "Add to Cart"
      @user = User.find(current_user.id)
      puts @user.carts.includes(:spec).where("spec_id=" + params[:spec_id]).length
      if @user.carts.includes(:spec).where("spec_id=" + params[:spec_id]).length != 0
        @cart = @user.carts.includes(:spec).where("spec_id=" + params[:spec_id])[0]
        @cart.quantity = @cart.quantity + params[:quantity].to_i
        @cart.amount = @cart.quantity * @cart.product.price
        @cart.save
      else 
        @cart = current_user.carts.create({user_id: current_user.id, product_id: @product.id, quantity: @quantity, amount: ((@product.price) * @quantity.to_i), spec_id: params[:spec_id]})
      end

      redirect_to product_path(@product), notice: "Added to cart successfully."
      # redirect_to carts_path(cart: {user_id: current_user.id, product_id: @product.id, quantity: @quantity, amount:((@product.price) * @quantity.to_i), spec: params[:spec]}), method: :post
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :sold, :image, :seller_id)
    end
end

project/app/helpers/products_helper.rb
module ProductsHelper
end

project/app/views/products/_form.html.erb
<div class="form">
  <%= form_with(model: product) do |form| %>

    <div class="form-field">
      <%= form.hidden_field :seller_id, value:current_user.id %>
    </div>

    <div class="form-field">
      <%= form.label :title %>
      <%= form.text_field :title, style: 'border-radius: 5px; padding:3px;', :required => true %>
    </div>

    <div class="form-field">
      <%= form.label :description %>
      <%= form.text_area :description, style: 'border-radius: 5px; padding:3px;', :required => true %>
    </div>

    <div class="form-field">
      <%= form.label :price %>
      <%= form.text_field :price, style: 'border-radius: 5px; padding:3px;', :required => true %>
    </div>

    <div class="form-field">
      <%= form.label "Choose an image" %>
      <%= form.file_field :image, style:'border-radius: 5px; margin:10px;'%>
    </div>

    <div class="actions" style="margin:30px;">
      <%= form.submit :Submit, style:'border-radius: 5px; height: 40px; width: 80%; margin-left: 10%;' %>
    </div>
  <% end %>
</div>

project/app/views/products/edit.html.erb
<h1 class="header-form">Editing Product</h1>

<%= render 'form', product: @product %>

<%#= link_to 'Show', @product %> |
<%#= link_to 'Back', products_path %>

project/app/views/products/index.html.erb
<h1 class="header" style="margin-bottom:20px;">Products</h1>

  <div class="row" style="display:flex; flex-wrap: wrap; flex-direction: row; width: 100%; box-sizing: border-box; margin: 0px;">
    <% @products.each do |product| %>
      <div class="column-md-3" style="position: relative; display:block; width: 25%; padding-right: 10px; padding-left: 10px; margin-bottom:10px; min-width:320px;">
      <div class="card card-product-grid" style="">
      <figcaption class="info-wrap" style="flex-direction: row;">
        <div style="text-align: center; width: 100%; height:300px; overflow:hidden;">
          <%= image_tag(product.image, :gravity =>"center", :height =>300 , :weight => 250, :crop=>"fill") %> 
        </div>

        <div class="link" style="margin:8px; font-weight:600; font-size:18px; overflow:hidden;height:30px;">
          <%= link_to product.title, product, style:"color: black; text-decoration:none; flex-wrap:nowrap;" %>
        </div>
        <div style="margin:8px; font-style:Italic; height:50px; overflow:hidden; ">
          <%= product.description %>
        </div>
        <div style="margin:8px; overflow:hidden;">
          $ <%= number_with_precision(product.price, precision: 2) %>
        </div>
        <div style="margin:8px; color:grey; font-style:Italic; overflow:hidden;">
          Sold : <%= product.sold %>
        </div>

        </figcaption>
      </div>
      </div>
    <% end %>
  </div>
<br>

<%# link_to 'New Product', new_product_path %>

project/app/views/products/new.html.erb
<h1 class="header-form">New Product</h1>

<%= render 'form', product: @product %>

<%#= link_to 'Back', products_path %>

project/app/views/products/show.html.erb
<div class="product-showbox">
  <div class="product-image">
    <%= image_tag(@product.image, :gravity =>"center", :height =>300 , :weight => 250, :crop=>"fill") %> 
  </div>

  <div class="product-detail">
    <p style="font-size:30px; font-family:serif; font-weight:600;">
      <strong><%= @product.title %></strong>
    </p>
    <hr style="width:80%">

    <p>
    <div style="width:80%;">
      <strong style="font-size:18px;">Description:</strong>
      <br>
      <span style="font-style:Italic;">
        <%= @product.description %>
      </span>
    </div>
    </p>

    <p>
      <strong style="font-size:18px;">Price: <br>$</strong>
      <%= number_with_precision(@product.price, precision: 2) %>
    </p>

    <p>
      <strong style="font-size:18px;">Sold: <br> x</strong>
        <%= @product.sold %>
    </p>

    <%= form_with url:products_do_path, method: :get do |form| %>
      <div class="product-specs">
        <% @specs.each do |spec, index| %>
          <input class="product-spec btn-check" type="radio" name="spec_id" id=<%= spec.id %> value=<%= spec.id %> required>
            <label class="btn product-spec" style="margin:3px;padding:5px;min-width:70px;" for=<%= spec.id %>>
              <%= spec.title %>
            </label>
            <% if user_signed_in? && current_user.seller? %>
              <button type="button" class="minus-by-one" style="margin:auto 20px auto 2px;">
                <%= link_to '-', product_spec_path(@product,spec), method: :delete, data:{confirm: "Are you sure ? "}, style:'text-decoration:none; color:black;' %>
              </button>
            <% end %>
        <% end %>
      </div>

        <br>
      
      <% if user_signed_in? == false || current_user.customer? %>
      <div>
          <input name="quantity" min="1" max="100" step="1" value="1" type="text" autocomplete="off" class="form-control" style="width:100px; margin:10px 20px; webkit-appearance: none;">
      </div>
      
      <input type="hidden" name="product_id" value=<%= @product.id%> >
      <div class="product-button-row">
        <div class="actions" style="margin:2px;">
          <input type="submit" name="commit" value="Add to Cart" label="Add to Cart" style='background-color: rgb(255, 159, 143); margin:5px; padding: 5px; border-radius: 10px; color: white;width: 150px;' >
        </div>

        <div class="actions" style="margin:2px;">
          <%= form.submit "Buy Now", style:'background-color: rgb(255, 159, 143); margin:5px; padding: 5px; border-radius: 10px; color: white; width: 150px;' %>
        </div>
      </div>

    <% end %>

      <div class="product-button-row">
      <% if user_signed_in? && current_user.customer? %>
        <button type="button" class="product-addCollection">
          <%= link_to 'Add to Collection', collections_path(collection: {user_id: current_user.id, product_id: @product.id}), method: :post, style:'text-decoration:none; color:black; margin:auto;'%> 
        </button>
      <% end %>
      </div>
    <% end %>

    <% if user_signed_in? && current_user.seller? %>
      <div>
        <button class="product-addSpec">
          <%= link_to 'Add Spec', new_product_spec_path(@product), style:'text-decoration:none; color:white; margin:auto;' %> 
        </button>
      </div>

      <div>
        <button class="product-edit">
          <%= link_to 'Edit Product', edit_product_path(@product), style:'text-decoration:none; color:white; margin:auto;' %> 
        </button>
      </div>

      <div>
        <button class="product-delete">
          <%= link_to 'Delete Product', product_path(@product), method: :delete, data:{confirm: "Are you sure ? "}, style:'text-decoration:none; color:white; margin:auto;' %> 
        </button>
      </div>
    <% end %>
  </div>
</div>

<hr style="width:90%; margin:20px auto;">

<div style="width:85%; margin:auto;">
<h1 class="header" style="">Comment</h1>
<% if @product.comments.empty? %>
<div style="background-color:gainsboro; border-radius:8px;padding:10px; margin:20px 0 100px 0;">
          No comment yet.
<div>
<% else %>
  <% @product.comments.each do |comment| %>
    <div style="background-color:gainsboro; border-radius:8px;padding:15px; margin:20px 0 100px 0;">
    <strong> <%= comment.user.email %> </strong>
    <hr>
      <%= comment.content %>
    </div>
  <% end %>
<% end %>